sudo: false
language: minimal
python:
  - '2.7'
  - '3.6'
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/miniconda
before_install:
  # don't install miniconda if it's already cached
  # if not yet installed, use different versions for py2 vs. py3
  - |
    if [ -f  $HOME/miniconda/bin]
      then
      echo "miniconda already installed"
    else
      rm -rf $HOME/miniconda
      if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]] then
        wget https://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
      else
        wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
      fi
      bash miniconda.sh -b -p $HOME/miniconda
      export PATH="$HOME/miniconda/bin:$PATH"
    fi
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
install:
  - >
      conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
      numpy nose pandas pylint pandoc
  - source activate test-environment
  # make sure we're using the correct version
  - python --version
  - pip install -r requirements.txt
  - pip install .
  - pip install pypandoc
  - pip install coveralls
script:
  - nosetests test --with-coverage --cover-package=gtfparse && ./lint.sh
after_success: coveralls
deploy:
  provider: pypi
  distributions: sdist
  user: openvax
  password: # See http://docs.travis-ci.com/user/encryption-keys/
    secure: "lNFheXNLXUin0p+1LUHpE6CPvLnv0WyaTW7nW+r3gbleI8AocJ3cbJPBExOioTLnyEw+hQsq/aJqaz4eeNoEwJKJi3OasuUuQf3sqF/ujOLTcap09NIknPIJBf0lseh1zQgEZr/ov18kiscY/nPKbXPqoGOINEyMEqYP+Cciiq3FokSD++BU1n55RpH4iya3//DmxuOlkgU0Idxv9KAPy13YP3eymPTix1NkEDwDVglevW4bpZqXjA2iQMzQg0HpwsfkvasrGQ6UZCyg/ukxMfuNna0Ws40frq8xrYz4NROrepwLZ+9XGpPY3/ts3EvMYURDmucAyqcdPmxoBXaKtFsg/C/4Dhqh0l/agXhls0hf9BjSuaZT+mWPXtB9LEjkoHFUIvsxGN53N9xoPABuhjudAJdbAr40/GWTnvJlkULmAJ+ZVHb7GHA39Xsk/Efys27vZeTpM8xjwtCaJ0i61FjWeJP09Rd9bk6QwrpbjjnuwpRl5qyJv9jSi8H+oMaxOWFaSDYEMPyhV3pjtXaGo2CgR8ypYg1g9EuqVmScP9N2L5YzhYmCzan7peqMhDqQFJwPjO5Ger99a5E88yytpqW3PhQG/5AJEV+d/ZGvn71FAnC+cEPJqy2+jrsRw0a04AMmJya2udRJMuzixnBvwbvc7BMNx0xis7LJxDgmOFg="
  on:
    branch: master
    condition: $TRAVIS_PYTHON_VERSION = "2.7"
